name: capture-kit

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - ".github/workflows/**"
      - "CaptureKit/**"
      - "CaptureKitTests/**"

jobs:
  Latest:
    name: Test Latest (macOS)
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.1.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "platform=macOS"
            name: "macOS"
            scheme: "CaptureKit"
            sdk: macosx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: brew bundle
      - name: Generate project
        run: xcodegen generate
      - name: ${{ matrix.name }}
        run: xcodebuild test -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}" clean -enableCodeCoverage YES -resultBundlePath "./${{ matrix.sdk }}.xcresult"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          xcode: true
          xcode_archive_path: "./${{ matrix.sdk }}.xcresult"